markdown: rdiscount
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Darktea
host: darktea.github.com
desc: Darktea

custom:
    category:
        notes: Notes
        reading: Reading
    categories:
      - name:  notes
        title: Notes

      - name:  reading
        title: Reading

meta:
    author:
        name: Darktea
        email: tiantianding@gmail.com
        disqus: Darktea              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: darktea                 # GitHub账号
        gravatar: 000000000  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
